### ISSUE TITLE
No static method compareUnsigned(II)I

### ISSUE THREAD

**Issue by horsejockey** [kotlin-graphics/kotlin-unsigned#10]
I am getting the following error in my crash logs.  

```
java.lang.NoSuchMethodError: No static method compareUnsigned(II)I in class Ljava/lang/Integer; or its super classes (declaration of 'java.lang.Integer' appears in /system/framework/core-libart.jar)
        at unsigned.Ushort.compareTo(Ushort.kt:87)
```
I'm not sure what this meant in the readme.  

```
All unsigned methods available for ints and longs on java 1.8 have been reported here.
These are offered directly on the corresponding Int and Long Kotlin primitives (with infix too)
```

It is crashing when I'm comparing two Ushorts using >=.

**Comment by elect86** [comment]
Hi Matthew,

I just added a [test](https://github.com/kotlin-graphics/kotlin-unsigned/commit/9391bf0afe17cd1bda7c0a1e5c2d433dff3452ef) for `Ushort` comparison and it works flawless

Can you show me some code?

> I'm not sure what this meant in the readme.

I meant that I copy/pasted all the unsigned methods from 1.8 (you can see them [here](https://github.com/kotlin-graphics/kotlin-unsigned/tree/master/src/main/kotlin/unsigned/java_1_7))
