### ISSUE TITLE
Extension operator functions for standard types

### ISSUE THREAD

**Issue by SerVB** [kotlin-graphics/kotlin-unsigned#11]
Hello!

Is it possible to provide some extension operator functions for standard types?
Something like `operator fun Int.plus(x: Uint): Int`.

Now I have to write `i + u.toInt()` instead of `i + u`.

**Comment by elect86** [comment]
Hi,

sure, anyway, most ones are already there (like [here](https://github.com/kotlin-graphics/kotlin-unsigned/blob/1a4da1076b385c3b81289278ed5b9d325f33507b/src/main/kotlin/unsigned/Int.kt))

You just have to write the `import` manually... Idea is a little weak here

**Comment by SerVB** [comment]
Thank you for the link and for the hint!
