### ISSUE TITLE
Aren't unsigned numbers in kotlin 1.3.x already?  

### ISSUE THREAD

**Issue by apatrida** [kotlin-graphics/kotlin-unsigned#17]
Not using unsigned numbers myself I can't be sure of all that there is available or not, but Kotlin 1.3 covers unsigned numbers doesn't it?  https://kotlinlang.org/docs/reference/whatsnew13.html#unsigned-integers

**Comment by elect86** [comment]
Yes, they actually are present

However this library was developed back into 2016 (published at very begin of 2017) and at that time there was yet no other way to get unsigned on Kotlin.

Moreover, in 1.3 (inline classes) they do not extend `Number`, making usage in some generic methods, such as in [glm](https://github.com/kotlin-graphics/glm), pretty impossible

I tried to suggest to convert `Number` from `abstract class` to `interface`, (inline classes can extends only interfaces) but the usage case was too irrilevant for them

**Comment by apatrida** [comment]
Yeah, I see this now:
https://github.com/Kotlin/KEEP/blob/master/proposals/unsigned-types.md#inheritance-from-number

**Comment by elect86** [comment]
I'm closing this
