### ISSUE TITLE
JitPack build failure for v3.3.32

### ISSUE THREAD

**Issue by Lucodivo** [kotlin-graphics/kotlin-unsigned#20]
Currently getting unresolved dependencies when attempting to use kotlin-glm due to its dependency on kotlin-unsigned.

Jitpack.io:
https://jitpack.io/#kotlin-graphics/kotlin-unsigned

Logs:
https://jitpack.io/com/github/kotlin-graphics/kotlin-unsigned/v3.3.32/build.log
"FAILURE: Build failed with an exception.

* What went wrong:
Task 'dokkaHtml' not found in root project 'unsigned'."

**Comment by elect86** [comment]
Hello Connor,

sorry, but Jitpack no more used

use [mary](https://github.com/kotlin-graphics/mary)
