### ISSUE TITLE
License missing

### ISSUE THREAD

**Issue by KenVanHoeylandt** [kotlin-graphics/kotlin-unsigned#4]
Hi! Please consider adding a license to your project.
Not having a license might prevent people from using your library.

**Comment by elect86** [comment]
Hi Ken!

Sure, just added

Thanks for pointing that out ;)

**Comment by elect86** [comment]
Ps: needed for CHIP-8?

Cool project btw 👍

**Comment by KenVanHoeylandt** [comment]
Thanks for adding a license! MIT is a nice choice 👍 

I am considering it for CHIP-8 indeed. Found out a bit late about `Byte` being signed in Kotlin :D
Thanks!
