### ISSUE TITLE
Maintain a latest release compiled with stable version of Kotlin

### ISSUE THREAD

**Issue by sachins** [kotlin-graphics/kotlin-unsigned#6]
It would be good to have one release with latest code that's compiled with stable Kotlin version. I can't use the latest release `v2.4.2` with stable Kotlin version `1.1.51` as of now. Last release I can use is `v2.3`.

**Comment by elect86** [comment]
Hi Sachin,

We just come back from the hospital where we had our first daughter.. My free time will be much less from now on..

I'd be glad if you could just jump in (I just sent you an invite)

**Comment by sachins** [comment]
Congratulations! Not in a hurry for this feature. I will look into it when I get a chance.

**Comment by elect86** [comment]
This became the norm now
